
## **ES E335 - Pre-requisite Test**
#### Author - Gaurav Shah

**1. How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.**

For matrix multiplication between (n,k) and (k, m) matrix:

$multiplications = n \times m \times k$

$additions = n \times m\times (k-1)$

On multiplying (n,k) and (k,m) matrix, resultant matrix dimensions are (n,m). For obtaining an element for the (n,m) matrix, say in row i and column j, we have to mulitply and add elements from $i^{th}$ row in (n,k) matrix with elements from $j^{th}$  which consists of **k** multiplications and **k-1** additons. Thus, to obtain all the elements of the (n,m) matrix, the total number of additions and multiplications will be as mentioned above. 

**2.Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?**

In [3]:
import numpy as np

In [4]:
#Let n = 2, m= 3, k = 2 
#Define the function for matrix multiplication 
def matrixmul(a,b):
    
    n= len(a)
    m= len(b[0])
    k= len(b)
    
    #Initialise the resultant matrix with zeroes
    res = np.zeros((n,m))
    
    for i in range(n):
        for j in range(m):
            for l in range(k):
                res[i][j] += (a[i][l]*b[l][j])
                
    return res

In [5]:
#Define the values a and b to test the defined function
a=[[1,1],[1,2]]
b=[[2,3,1],[1,2,3]]

c= matrixmul(a,b)

print(c) 

[[3. 5. 4.]
 [4. 7. 7.]]


In [6]:
#Matrix Multiplication using numpy
res_np = np.dot(a,b)
print(c)

[[3. 5. 4.]
 [4. 7. 7.]]


Now, we can time both approaches using larger values of n,m and randomly assigning values to elements of a,b matrices as with smaller values of n,m and k, the %timeit command won't be able to time the code snippet properly.

In [7]:
n=15
m=10
k=20

#Matrix a with dimension (15,20)
a= np.random.randint(20, size=(n,k))
#Matrix b with dimensions (20,10)
b= np.random.randint(20, size=(k,m))

In [8]:
#Timing the matrixmul() funtion
%timeit c=matrixmul(a,b)

1.64 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
#Timinig the matrix multiplication using numpy
%timeit c=np.dot(a,b)

2.3 µs ± 92.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


- List method is much slower than numpy because it's not Optimized. NumPy matrix multiplication uses optimised C code and also use vectorization resulting in faster implementation. 